# Python CircleCI 2.0 configuration file
version: 2
orbs:
      codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo  pip install pipenv
            pipenv --three
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv run pytest -v --cov ./adventure
      - run:
          name: return codecoverage metric
          command: | 
              pipenv run codecov
  deploy:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
