# Generated by Django 3.0rc1 on 2019-11-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventure", "0002_item_monster"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="inventory",
            field=models.ManyToManyField(to="adventure.Item"),
        ),
        migrations.AddField(
            model_name="room",
            name="inventory",
            field=models.ManyToManyField(to="adventure.Item"),
        ),
    ]
