# Generated by Django 3.0rc1 on 2019-11-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adventure", "0003_auto_20191120_0133"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player", old_name="currentRoom", new_name="current_room",
        ),
    ]
