# Generated by Django 3.0rc1 on 2019-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventure", "0004_auto_20191120_0507"),
    ]

    operations = [
        migrations.AddField(
            model_name="item", name="description", field=models.TextField(null=True),
        ),
    ]
